name: Deploy to Production

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linter
        run: npm run lint
        
      # Temporarily disabled due to existing type errors
      # - name: Type check
      #   run: npm run type-check
        
      # Database is shipped with the repo, just verify it exists
      - name: Verify production database
        run: |
          if [ ! -f journey-public.db ]; then
            echo "Error: Production database not found in repository"
            echo "Please run 'npm run db:create-prod' locally and commit journey-public.db"
            exit 1
          fi
          echo "✓ Production database found"
          echo "  Size: $(ls -lh journey-public.db | awk '{print $5}')"
          echo "  Last modified: $(date -r journey-public.db)"
        
      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production
          
      # Deployment Strategy:
      # Currently using Vercel's automatic GitHub integration
      # For production environments, consider using GitHub Actions controlled deployment
      # See docs/proposals/deployment-strategy-comparison.md for details
      
      # To enable GitHub Actions deployment:
      # 1. Disable Vercel GitHub integration in Vercel dashboard
      # 2. Add secrets: VERCEL_TOKEN, VERCEL_ORG_ID, VERCEL_PROJECT_ID
      # 3. Uncomment the deployment step below
      
      # - name: Deploy to Vercel Production
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   environment: production  # Optional: adds approval requirements
      #   run: |
      #     npm install -g vercel
      #     vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
      #   env:
      #     VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      #     VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          
      # Optional: Commit updated production database back to repo
      # Uncomment if you want CI to update the database automatically
      # - name: Commit production database
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add journey-public.db
      #     git diff --staged --quiet || git commit -m "Update production database [skip ci]"
      #     git push
